global.CONST_DIPLOMACY_MEMORY_ROOT = '__diplomacy__';
global.CONST_DIPLOMACY_USER_DEFAULT_CPU = 2;
global.CONST_DIPLOMACY_USER_DEFAULT_BUCKET_INCREASE = 0.2;
global.CONST_DIPLOMACY_USER_DIPLOMACY_STATUS = {};

// Diplomacy status \\
global.CONST_DIPLOMACY_USER_DIPLOMACY_STATUS_ENEMY = -1;
global.CONST_DIPLOMACY_USER_DIPLOMACY_STATUS_NEUTRAL = 0;
global.CONST_DIPLOMACY_USER_DIPLOMACY_STATUS_FRIENDLY = 1;

global.CONST_DIPLOMACY_USER_DIPLOMACY_STATUS_DEFAULT = 0;

// Keep sorted from hostile to friendly
global.CONST_DIPLOMACY_USER_DIPLOMACY_STATUS[CONST_DIPLOMACY_USER_DIPLOMACY_STATUS_ENEMY] = -0.5;
global.CONST_DIPLOMACY_USER_DIPLOMACY_STATUS[CONST_DIPLOMACY_USER_DIPLOMACY_STATUS_NEUTRAL] = 0.5;
global.CONST_DIPLOMACY_USER_DIPLOMACY_STATUS[CONST_DIPLOMACY_USER_DIPLOMACY_STATUS_FRIENDLY] = 1;
// \\ Diplomacy status // \\